name: ✨ Feature Request ✨
description: 🌟 Suggest a new feature or enhancement
labels:
  - type:feature
  - status:new
body:
  - type: textarea
    id: description
    attributes:
      label: Feature Description
      description: A clear, concise description of the feature you want.
    validations:
      required: true

  - type: textarea
    id: motivation
    attributes:
      label: Motivation / Use Case
      description: Explain why this feature would be useful and what problem it solves.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you have considered.
    validations:
      required: false

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Add any other context, mockups, or screenshots.
    validations:
      required: false
